// Code generated by Prisma (prisma@1.34.0). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from "graphql";
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model
} from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export type Maybe<T> = T | undefined | null;

export interface Exists {
  branch: (where?: BranchWhereInput) => Promise<boolean>;
  campus: (where?: CampusWhereInput) => Promise<boolean>;
  course: (where?: CourseWhereInput) => Promise<boolean>;
  global: (where?: GlobalWhereInput) => Promise<boolean>;
  questionAdd: (where?: QuestionAddWhereInput) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;

  /**
   * Queries
   */

  branch: (where: BranchWhereUniqueInput) => BranchNullablePromise;
  branches: (args?: {
    where?: BranchWhereInput;
    orderBy?: BranchOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Branch>;
  branchesConnection: (args?: {
    where?: BranchWhereInput;
    orderBy?: BranchOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => BranchConnectionPromise;
  campus: (where: CampusWhereUniqueInput) => CampusNullablePromise;
  campuses: (args?: {
    where?: CampusWhereInput;
    orderBy?: CampusOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Campus>;
  campusesConnection: (args?: {
    where?: CampusWhereInput;
    orderBy?: CampusOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => CampusConnectionPromise;
  course: (where: CourseWhereUniqueInput) => CourseNullablePromise;
  courses: (args?: {
    where?: CourseWhereInput;
    orderBy?: CourseOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Course>;
  coursesConnection: (args?: {
    where?: CourseWhereInput;
    orderBy?: CourseOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => CourseConnectionPromise;
  global: (where: GlobalWhereUniqueInput) => GlobalNullablePromise;
  globals: (args?: {
    where?: GlobalWhereInput;
    orderBy?: GlobalOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Global>;
  globalsConnection: (args?: {
    where?: GlobalWhereInput;
    orderBy?: GlobalOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => GlobalConnectionPromise;
  questionAdd: (
    where: QuestionAddWhereUniqueInput
  ) => QuestionAddNullablePromise;
  questionAdds: (args?: {
    where?: QuestionAddWhereInput;
    orderBy?: QuestionAddOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<QuestionAdd>;
  questionAddsConnection: (args?: {
    where?: QuestionAddWhereInput;
    orderBy?: QuestionAddOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => QuestionAddConnectionPromise;
  user: (where: UserWhereUniqueInput) => UserNullablePromise;
  users: (args?: {
    where?: UserWhereInput;
    orderBy?: UserOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<User>;
  usersConnection: (args?: {
    where?: UserWhereInput;
    orderBy?: UserOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => UserConnectionPromise;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createBranch: (data: BranchCreateInput) => BranchPromise;
  updateBranch: (args: {
    data: BranchUpdateInput;
    where: BranchWhereUniqueInput;
  }) => BranchPromise;
  updateManyBranches: (args: {
    data: BranchUpdateManyMutationInput;
    where?: BranchWhereInput;
  }) => BatchPayloadPromise;
  upsertBranch: (args: {
    where: BranchWhereUniqueInput;
    create: BranchCreateInput;
    update: BranchUpdateInput;
  }) => BranchPromise;
  deleteBranch: (where: BranchWhereUniqueInput) => BranchPromise;
  deleteManyBranches: (where?: BranchWhereInput) => BatchPayloadPromise;
  createCampus: (data: CampusCreateInput) => CampusPromise;
  updateCampus: (args: {
    data: CampusUpdateInput;
    where: CampusWhereUniqueInput;
  }) => CampusPromise;
  updateManyCampuses: (args: {
    data: CampusUpdateManyMutationInput;
    where?: CampusWhereInput;
  }) => BatchPayloadPromise;
  upsertCampus: (args: {
    where: CampusWhereUniqueInput;
    create: CampusCreateInput;
    update: CampusUpdateInput;
  }) => CampusPromise;
  deleteCampus: (where: CampusWhereUniqueInput) => CampusPromise;
  deleteManyCampuses: (where?: CampusWhereInput) => BatchPayloadPromise;
  createCourse: (data: CourseCreateInput) => CoursePromise;
  updateCourse: (args: {
    data: CourseUpdateInput;
    where: CourseWhereUniqueInput;
  }) => CoursePromise;
  updateManyCourses: (args: {
    data: CourseUpdateManyMutationInput;
    where?: CourseWhereInput;
  }) => BatchPayloadPromise;
  upsertCourse: (args: {
    where: CourseWhereUniqueInput;
    create: CourseCreateInput;
    update: CourseUpdateInput;
  }) => CoursePromise;
  deleteCourse: (where: CourseWhereUniqueInput) => CoursePromise;
  deleteManyCourses: (where?: CourseWhereInput) => BatchPayloadPromise;
  createGlobal: (data: GlobalCreateInput) => GlobalPromise;
  updateGlobal: (args: {
    data: GlobalUpdateInput;
    where: GlobalWhereUniqueInput;
  }) => GlobalPromise;
  updateManyGlobals: (args: {
    data: GlobalUpdateManyMutationInput;
    where?: GlobalWhereInput;
  }) => BatchPayloadPromise;
  upsertGlobal: (args: {
    where: GlobalWhereUniqueInput;
    create: GlobalCreateInput;
    update: GlobalUpdateInput;
  }) => GlobalPromise;
  deleteGlobal: (where: GlobalWhereUniqueInput) => GlobalPromise;
  deleteManyGlobals: (where?: GlobalWhereInput) => BatchPayloadPromise;
  createQuestionAdd: (data: QuestionAddCreateInput) => QuestionAddPromise;
  updateQuestionAdd: (args: {
    data: QuestionAddUpdateInput;
    where: QuestionAddWhereUniqueInput;
  }) => QuestionAddPromise;
  updateManyQuestionAdds: (args: {
    data: QuestionAddUpdateManyMutationInput;
    where?: QuestionAddWhereInput;
  }) => BatchPayloadPromise;
  upsertQuestionAdd: (args: {
    where: QuestionAddWhereUniqueInput;
    create: QuestionAddCreateInput;
    update: QuestionAddUpdateInput;
  }) => QuestionAddPromise;
  deleteQuestionAdd: (where: QuestionAddWhereUniqueInput) => QuestionAddPromise;
  deleteManyQuestionAdds: (
    where?: QuestionAddWhereInput
  ) => BatchPayloadPromise;
  createUser: (data: UserCreateInput) => UserPromise;
  updateUser: (args: {
    data: UserUpdateInput;
    where: UserWhereUniqueInput;
  }) => UserPromise;
  updateManyUsers: (args: {
    data: UserUpdateManyMutationInput;
    where?: UserWhereInput;
  }) => BatchPayloadPromise;
  upsertUser: (args: {
    where: UserWhereUniqueInput;
    create: UserCreateInput;
    update: UserUpdateInput;
  }) => UserPromise;
  deleteUser: (where: UserWhereUniqueInput) => UserPromise;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayloadPromise;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  branch: (
    where?: BranchSubscriptionWhereInput
  ) => BranchSubscriptionPayloadSubscription;
  campus: (
    where?: CampusSubscriptionWhereInput
  ) => CampusSubscriptionPayloadSubscription;
  course: (
    where?: CourseSubscriptionWhereInput
  ) => CourseSubscriptionPayloadSubscription;
  global: (
    where?: GlobalSubscriptionWhereInput
  ) => GlobalSubscriptionPayloadSubscription;
  questionAdd: (
    where?: QuestionAddSubscriptionWhereInput
  ) => QuestionAddSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type BranchOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC";

export type CampusOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "admin_id_ASC"
  | "admin_id_DESC"
  | "name_ASC"
  | "name_DESC";

export type CourseOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "branch_ASC"
  | "branch_DESC"
  | "coordinator_id_ASC"
  | "coordinator_id_DESC"
  | "name_ASC"
  | "name_DESC";

export type GlobalOrderByInput =
  | "regs_ASC"
  | "regs_DESC"
  | "regf_ASC"
  | "regf_DESC"
  | "id_ASC"
  | "id_DESC"
  | "_id_ASC"
  | "_id_DESC";

export type QuestionAddOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "course_ASC"
  | "course_DESC"
  | "name_ASC"
  | "name_DESC"
  | "desc_ASC"
  | "desc_DESC"
  | "exp_ASC"
  | "exp_DESC"
  | "ans_ASC"
  | "ans_DESC";

export type UserOrderByInput =
  | "username_ASC"
  | "username_DESC"
  | "password_ASC"
  | "password_DESC"
  | "name_ASC"
  | "name_DESC"
  | "campus_ASC"
  | "campus_DESC"
  | "department_ASC"
  | "department_DESC"
  | "dob_ASC"
  | "dob_DESC"
  | "email_ASC"
  | "email_DESC"
  | "level_ASC"
  | "level_DESC"
  | "id_ASC"
  | "id_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export type BranchWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
  name?: Maybe<String>;
}>;

export interface BranchWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  AND?: Maybe<BranchWhereInput[] | BranchWhereInput>;
}

export type CampusWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
  name?: Maybe<String>;
}>;

export interface CampusWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  admin_id?: Maybe<String>;
  admin_id_not?: Maybe<String>;
  admin_id_in?: Maybe<String[] | String>;
  admin_id_not_in?: Maybe<String[] | String>;
  admin_id_lt?: Maybe<String>;
  admin_id_lte?: Maybe<String>;
  admin_id_gt?: Maybe<String>;
  admin_id_gte?: Maybe<String>;
  admin_id_contains?: Maybe<String>;
  admin_id_not_contains?: Maybe<String>;
  admin_id_starts_with?: Maybe<String>;
  admin_id_not_starts_with?: Maybe<String>;
  admin_id_ends_with?: Maybe<String>;
  admin_id_not_ends_with?: Maybe<String>;
  departments_some?: Maybe<TagWhereInput>;
  departments_every?: Maybe<TagRestrictedWhereInput>;
  departments_none?: Maybe<TagRestrictedWhereInput>;
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  AND?: Maybe<CampusWhereInput[] | CampusWhereInput>;
}

export interface TagWhereInput {
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<TagWhereInput[] | TagWhereInput>;
}

export interface TagRestrictedWhereInput {
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<TagRestrictedWhereInput[] | TagRestrictedWhereInput>;
}

export type CourseWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
  name?: Maybe<String>;
}>;

export interface CourseWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  branch?: Maybe<String>;
  branch_not?: Maybe<String>;
  branch_in?: Maybe<String[] | String>;
  branch_not_in?: Maybe<String[] | String>;
  branch_lt?: Maybe<String>;
  branch_lte?: Maybe<String>;
  branch_gt?: Maybe<String>;
  branch_gte?: Maybe<String>;
  branch_contains?: Maybe<String>;
  branch_not_contains?: Maybe<String>;
  branch_starts_with?: Maybe<String>;
  branch_not_starts_with?: Maybe<String>;
  branch_ends_with?: Maybe<String>;
  branch_not_ends_with?: Maybe<String>;
  coordinator_id?: Maybe<String>;
  coordinator_id_not?: Maybe<String>;
  coordinator_id_in?: Maybe<String[] | String>;
  coordinator_id_not_in?: Maybe<String[] | String>;
  coordinator_id_lt?: Maybe<String>;
  coordinator_id_lte?: Maybe<String>;
  coordinator_id_gt?: Maybe<String>;
  coordinator_id_gte?: Maybe<String>;
  coordinator_id_contains?: Maybe<String>;
  coordinator_id_not_contains?: Maybe<String>;
  coordinator_id_starts_with?: Maybe<String>;
  coordinator_id_not_starts_with?: Maybe<String>;
  coordinator_id_ends_with?: Maybe<String>;
  coordinator_id_not_ends_with?: Maybe<String>;
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  AND?: Maybe<CourseWhereInput[] | CourseWhereInput>;
}

export type GlobalWhereUniqueInput = AtLeastOne<{
  id: Maybe<String>;
  _id?: Maybe<ID_Input>;
}>;

export interface GlobalWhereInput {
  regs?: Maybe<Boolean>;
  regs_not?: Maybe<Boolean>;
  regf?: Maybe<Boolean>;
  regf_not?: Maybe<Boolean>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  _id?: Maybe<ID_Input>;
  _id_not?: Maybe<ID_Input>;
  _id_in?: Maybe<ID_Input[] | ID_Input>;
  _id_not_in?: Maybe<ID_Input[] | ID_Input>;
  _id_lt?: Maybe<ID_Input>;
  _id_lte?: Maybe<ID_Input>;
  _id_gt?: Maybe<ID_Input>;
  _id_gte?: Maybe<ID_Input>;
  _id_contains?: Maybe<ID_Input>;
  _id_not_contains?: Maybe<ID_Input>;
  _id_starts_with?: Maybe<ID_Input>;
  _id_not_starts_with?: Maybe<ID_Input>;
  _id_ends_with?: Maybe<ID_Input>;
  _id_not_ends_with?: Maybe<ID_Input>;
  AND?: Maybe<GlobalWhereInput[] | GlobalWhereInput>;
}

export type QuestionAddWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
}>;

export interface QuestionAddWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  course?: Maybe<String>;
  course_not?: Maybe<String>;
  course_in?: Maybe<String[] | String>;
  course_not_in?: Maybe<String[] | String>;
  course_lt?: Maybe<String>;
  course_lte?: Maybe<String>;
  course_gt?: Maybe<String>;
  course_gte?: Maybe<String>;
  course_contains?: Maybe<String>;
  course_not_contains?: Maybe<String>;
  course_starts_with?: Maybe<String>;
  course_not_starts_with?: Maybe<String>;
  course_ends_with?: Maybe<String>;
  course_not_ends_with?: Maybe<String>;
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  desc?: Maybe<String>;
  desc_not?: Maybe<String>;
  desc_in?: Maybe<String[] | String>;
  desc_not_in?: Maybe<String[] | String>;
  desc_lt?: Maybe<String>;
  desc_lte?: Maybe<String>;
  desc_gt?: Maybe<String>;
  desc_gte?: Maybe<String>;
  desc_contains?: Maybe<String>;
  desc_not_contains?: Maybe<String>;
  desc_starts_with?: Maybe<String>;
  desc_not_starts_with?: Maybe<String>;
  desc_ends_with?: Maybe<String>;
  desc_not_ends_with?: Maybe<String>;
  exp?: Maybe<String>;
  exp_not?: Maybe<String>;
  exp_in?: Maybe<String[] | String>;
  exp_not_in?: Maybe<String[] | String>;
  exp_lt?: Maybe<String>;
  exp_lte?: Maybe<String>;
  exp_gt?: Maybe<String>;
  exp_gte?: Maybe<String>;
  exp_contains?: Maybe<String>;
  exp_not_contains?: Maybe<String>;
  exp_starts_with?: Maybe<String>;
  exp_not_starts_with?: Maybe<String>;
  exp_ends_with?: Maybe<String>;
  exp_not_ends_with?: Maybe<String>;
  opt_some?: Maybe<ObjWhereInput>;
  opt_every?: Maybe<ObjRestrictedWhereInput>;
  opt_none?: Maybe<ObjRestrictedWhereInput>;
  ans?: Maybe<String>;
  ans_not?: Maybe<String>;
  ans_in?: Maybe<String[] | String>;
  ans_not_in?: Maybe<String[] | String>;
  ans_lt?: Maybe<String>;
  ans_lte?: Maybe<String>;
  ans_gt?: Maybe<String>;
  ans_gte?: Maybe<String>;
  ans_contains?: Maybe<String>;
  ans_not_contains?: Maybe<String>;
  ans_starts_with?: Maybe<String>;
  ans_not_starts_with?: Maybe<String>;
  ans_ends_with?: Maybe<String>;
  ans_not_ends_with?: Maybe<String>;
  AND?: Maybe<QuestionAddWhereInput[] | QuestionAddWhereInput>;
}

export interface ObjWhereInput {
  opt1?: Maybe<String>;
  opt1_not?: Maybe<String>;
  opt1_in?: Maybe<String[] | String>;
  opt1_not_in?: Maybe<String[] | String>;
  opt1_lt?: Maybe<String>;
  opt1_lte?: Maybe<String>;
  opt1_gt?: Maybe<String>;
  opt1_gte?: Maybe<String>;
  opt1_contains?: Maybe<String>;
  opt1_not_contains?: Maybe<String>;
  opt1_starts_with?: Maybe<String>;
  opt1_not_starts_with?: Maybe<String>;
  opt1_ends_with?: Maybe<String>;
  opt1_not_ends_with?: Maybe<String>;
  opt2?: Maybe<String>;
  opt2_not?: Maybe<String>;
  opt2_in?: Maybe<String[] | String>;
  opt2_not_in?: Maybe<String[] | String>;
  opt2_lt?: Maybe<String>;
  opt2_lte?: Maybe<String>;
  opt2_gt?: Maybe<String>;
  opt2_gte?: Maybe<String>;
  opt2_contains?: Maybe<String>;
  opt2_not_contains?: Maybe<String>;
  opt2_starts_with?: Maybe<String>;
  opt2_not_starts_with?: Maybe<String>;
  opt2_ends_with?: Maybe<String>;
  opt2_not_ends_with?: Maybe<String>;
  opt3?: Maybe<String>;
  opt3_not?: Maybe<String>;
  opt3_in?: Maybe<String[] | String>;
  opt3_not_in?: Maybe<String[] | String>;
  opt3_lt?: Maybe<String>;
  opt3_lte?: Maybe<String>;
  opt3_gt?: Maybe<String>;
  opt3_gte?: Maybe<String>;
  opt3_contains?: Maybe<String>;
  opt3_not_contains?: Maybe<String>;
  opt3_starts_with?: Maybe<String>;
  opt3_not_starts_with?: Maybe<String>;
  opt3_ends_with?: Maybe<String>;
  opt3_not_ends_with?: Maybe<String>;
  opt4?: Maybe<String>;
  opt4_not?: Maybe<String>;
  opt4_in?: Maybe<String[] | String>;
  opt4_not_in?: Maybe<String[] | String>;
  opt4_lt?: Maybe<String>;
  opt4_lte?: Maybe<String>;
  opt4_gt?: Maybe<String>;
  opt4_gte?: Maybe<String>;
  opt4_contains?: Maybe<String>;
  opt4_not_contains?: Maybe<String>;
  opt4_starts_with?: Maybe<String>;
  opt4_not_starts_with?: Maybe<String>;
  opt4_ends_with?: Maybe<String>;
  opt4_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<ObjWhereInput[] | ObjWhereInput>;
}

export interface ObjRestrictedWhereInput {
  opt1?: Maybe<String>;
  opt1_not?: Maybe<String>;
  opt1_in?: Maybe<String[] | String>;
  opt1_not_in?: Maybe<String[] | String>;
  opt1_lt?: Maybe<String>;
  opt1_lte?: Maybe<String>;
  opt1_gt?: Maybe<String>;
  opt1_gte?: Maybe<String>;
  opt1_contains?: Maybe<String>;
  opt1_not_contains?: Maybe<String>;
  opt1_starts_with?: Maybe<String>;
  opt1_not_starts_with?: Maybe<String>;
  opt1_ends_with?: Maybe<String>;
  opt1_not_ends_with?: Maybe<String>;
  opt2?: Maybe<String>;
  opt2_not?: Maybe<String>;
  opt2_in?: Maybe<String[] | String>;
  opt2_not_in?: Maybe<String[] | String>;
  opt2_lt?: Maybe<String>;
  opt2_lte?: Maybe<String>;
  opt2_gt?: Maybe<String>;
  opt2_gte?: Maybe<String>;
  opt2_contains?: Maybe<String>;
  opt2_not_contains?: Maybe<String>;
  opt2_starts_with?: Maybe<String>;
  opt2_not_starts_with?: Maybe<String>;
  opt2_ends_with?: Maybe<String>;
  opt2_not_ends_with?: Maybe<String>;
  opt3?: Maybe<String>;
  opt3_not?: Maybe<String>;
  opt3_in?: Maybe<String[] | String>;
  opt3_not_in?: Maybe<String[] | String>;
  opt3_lt?: Maybe<String>;
  opt3_lte?: Maybe<String>;
  opt3_gt?: Maybe<String>;
  opt3_gte?: Maybe<String>;
  opt3_contains?: Maybe<String>;
  opt3_not_contains?: Maybe<String>;
  opt3_starts_with?: Maybe<String>;
  opt3_not_starts_with?: Maybe<String>;
  opt3_ends_with?: Maybe<String>;
  opt3_not_ends_with?: Maybe<String>;
  opt4?: Maybe<String>;
  opt4_not?: Maybe<String>;
  opt4_in?: Maybe<String[] | String>;
  opt4_not_in?: Maybe<String[] | String>;
  opt4_lt?: Maybe<String>;
  opt4_lte?: Maybe<String>;
  opt4_gt?: Maybe<String>;
  opt4_gte?: Maybe<String>;
  opt4_contains?: Maybe<String>;
  opt4_not_contains?: Maybe<String>;
  opt4_starts_with?: Maybe<String>;
  opt4_not_starts_with?: Maybe<String>;
  opt4_ends_with?: Maybe<String>;
  opt4_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<ObjRestrictedWhereInput[] | ObjRestrictedWhereInput>;
}

export type UserWhereUniqueInput = AtLeastOne<{
  username: Maybe<String>;
  id?: Maybe<ID_Input>;
}>;

export interface UserWhereInput {
  username?: Maybe<String>;
  username_not?: Maybe<String>;
  username_in?: Maybe<String[] | String>;
  username_not_in?: Maybe<String[] | String>;
  username_lt?: Maybe<String>;
  username_lte?: Maybe<String>;
  username_gt?: Maybe<String>;
  username_gte?: Maybe<String>;
  username_contains?: Maybe<String>;
  username_not_contains?: Maybe<String>;
  username_starts_with?: Maybe<String>;
  username_not_starts_with?: Maybe<String>;
  username_ends_with?: Maybe<String>;
  username_not_ends_with?: Maybe<String>;
  password?: Maybe<String>;
  password_not?: Maybe<String>;
  password_in?: Maybe<String[] | String>;
  password_not_in?: Maybe<String[] | String>;
  password_lt?: Maybe<String>;
  password_lte?: Maybe<String>;
  password_gt?: Maybe<String>;
  password_gte?: Maybe<String>;
  password_contains?: Maybe<String>;
  password_not_contains?: Maybe<String>;
  password_starts_with?: Maybe<String>;
  password_not_starts_with?: Maybe<String>;
  password_ends_with?: Maybe<String>;
  password_not_ends_with?: Maybe<String>;
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  campus?: Maybe<String>;
  campus_not?: Maybe<String>;
  campus_in?: Maybe<String[] | String>;
  campus_not_in?: Maybe<String[] | String>;
  campus_lt?: Maybe<String>;
  campus_lte?: Maybe<String>;
  campus_gt?: Maybe<String>;
  campus_gte?: Maybe<String>;
  campus_contains?: Maybe<String>;
  campus_not_contains?: Maybe<String>;
  campus_starts_with?: Maybe<String>;
  campus_not_starts_with?: Maybe<String>;
  campus_ends_with?: Maybe<String>;
  campus_not_ends_with?: Maybe<String>;
  department?: Maybe<String>;
  department_not?: Maybe<String>;
  department_in?: Maybe<String[] | String>;
  department_not_in?: Maybe<String[] | String>;
  department_lt?: Maybe<String>;
  department_lte?: Maybe<String>;
  department_gt?: Maybe<String>;
  department_gte?: Maybe<String>;
  department_contains?: Maybe<String>;
  department_not_contains?: Maybe<String>;
  department_starts_with?: Maybe<String>;
  department_not_starts_with?: Maybe<String>;
  department_ends_with?: Maybe<String>;
  department_not_ends_with?: Maybe<String>;
  dob?: Maybe<DateTimeInput>;
  dob_not?: Maybe<DateTimeInput>;
  dob_in?: Maybe<DateTimeInput[] | DateTimeInput>;
  dob_not_in?: Maybe<DateTimeInput[] | DateTimeInput>;
  dob_lt?: Maybe<DateTimeInput>;
  dob_lte?: Maybe<DateTimeInput>;
  dob_gt?: Maybe<DateTimeInput>;
  dob_gte?: Maybe<DateTimeInput>;
  email?: Maybe<String>;
  email_not?: Maybe<String>;
  email_in?: Maybe<String[] | String>;
  email_not_in?: Maybe<String[] | String>;
  email_lt?: Maybe<String>;
  email_lte?: Maybe<String>;
  email_gt?: Maybe<String>;
  email_gte?: Maybe<String>;
  email_contains?: Maybe<String>;
  email_not_contains?: Maybe<String>;
  email_starts_with?: Maybe<String>;
  email_not_starts_with?: Maybe<String>;
  email_ends_with?: Maybe<String>;
  email_not_ends_with?: Maybe<String>;
  level?: Maybe<Int>;
  level_not?: Maybe<Int>;
  level_in?: Maybe<Int[] | Int>;
  level_not_in?: Maybe<Int[] | Int>;
  level_lt?: Maybe<Int>;
  level_lte?: Maybe<Int>;
  level_gt?: Maybe<Int>;
  level_gte?: Maybe<Int>;
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  AND?: Maybe<UserWhereInput[] | UserWhereInput>;
}

export interface BranchCreateInput {
  id?: Maybe<ID_Input>;
  name: String;
}

export interface BranchUpdateInput {
  name?: Maybe<String>;
}

export interface BranchUpdateManyMutationInput {
  name?: Maybe<String>;
}

export interface CampusCreateInput {
  id?: Maybe<ID_Input>;
  admin_id: String;
  departments?: Maybe<TagCreateManyInput>;
  name: String;
}

export interface TagCreateManyInput {
  create?: Maybe<TagCreateInput[] | TagCreateInput>;
}

export interface TagCreateInput {
  name: String;
  id: String;
}

export interface CampusUpdateInput {
  admin_id?: Maybe<String>;
  departments?: Maybe<TagUpdateManyInput>;
  name?: Maybe<String>;
}

export interface TagUpdateManyInput {
  create?: Maybe<TagCreateInput[] | TagCreateInput>;
  deleteMany?: Maybe<TagScalarWhereInput[] | TagScalarWhereInput>;
  updateMany?: Maybe<
    TagUpdateManyWithWhereNestedInput[] | TagUpdateManyWithWhereNestedInput
  >;
}

export interface TagScalarWhereInput {
  name?: Maybe<String>;
  name_not?: Maybe<String>;
  name_in?: Maybe<String[] | String>;
  name_not_in?: Maybe<String[] | String>;
  name_lt?: Maybe<String>;
  name_lte?: Maybe<String>;
  name_gt?: Maybe<String>;
  name_gte?: Maybe<String>;
  name_contains?: Maybe<String>;
  name_not_contains?: Maybe<String>;
  name_starts_with?: Maybe<String>;
  name_not_starts_with?: Maybe<String>;
  name_ends_with?: Maybe<String>;
  name_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<TagScalarWhereInput[] | TagScalarWhereInput>;
  OR?: Maybe<TagScalarWhereInput[] | TagScalarWhereInput>;
  NOT?: Maybe<TagScalarWhereInput[] | TagScalarWhereInput>;
}

export interface TagUpdateManyWithWhereNestedInput {
  where: TagScalarWhereInput;
  data: TagUpdateManyDataInput;
}

export interface TagUpdateManyDataInput {
  name?: Maybe<String>;
  id?: Maybe<String>;
}

export interface CampusUpdateManyMutationInput {
  admin_id?: Maybe<String>;
  name?: Maybe<String>;
}

export interface CourseCreateInput {
  id?: Maybe<ID_Input>;
  branch: String;
  coordinator_id: String;
  name: String;
}

export interface CourseUpdateInput {
  branch?: Maybe<String>;
  coordinator_id?: Maybe<String>;
  name?: Maybe<String>;
}

export interface CourseUpdateManyMutationInput {
  branch?: Maybe<String>;
  coordinator_id?: Maybe<String>;
  name?: Maybe<String>;
}

export interface GlobalCreateInput {
  regs?: Maybe<Boolean>;
  regf?: Maybe<Boolean>;
  id?: Maybe<String>;
  _id?: Maybe<ID_Input>;
}

export interface GlobalUpdateInput {
  regs?: Maybe<Boolean>;
  regf?: Maybe<Boolean>;
  id?: Maybe<String>;
}

export interface GlobalUpdateManyMutationInput {
  regs?: Maybe<Boolean>;
  regf?: Maybe<Boolean>;
  id?: Maybe<String>;
}

export interface QuestionAddCreateInput {
  id?: Maybe<ID_Input>;
  course: String;
  name: String;
  desc: String;
  exp: String;
  opt?: Maybe<ObjCreateManyInput>;
  ans: String;
}

export interface ObjCreateManyInput {
  create?: Maybe<ObjCreateInput[] | ObjCreateInput>;
}

export interface ObjCreateInput {
  opt1: String;
  opt2: String;
  opt3: String;
  opt4: String;
  id: String;
}

export interface QuestionAddUpdateInput {
  course?: Maybe<String>;
  name?: Maybe<String>;
  desc?: Maybe<String>;
  exp?: Maybe<String>;
  opt?: Maybe<ObjUpdateManyInput>;
  ans?: Maybe<String>;
}

export interface ObjUpdateManyInput {
  create?: Maybe<ObjCreateInput[] | ObjCreateInput>;
  deleteMany?: Maybe<ObjScalarWhereInput[] | ObjScalarWhereInput>;
  updateMany?: Maybe<
    ObjUpdateManyWithWhereNestedInput[] | ObjUpdateManyWithWhereNestedInput
  >;
}

export interface ObjScalarWhereInput {
  opt1?: Maybe<String>;
  opt1_not?: Maybe<String>;
  opt1_in?: Maybe<String[] | String>;
  opt1_not_in?: Maybe<String[] | String>;
  opt1_lt?: Maybe<String>;
  opt1_lte?: Maybe<String>;
  opt1_gt?: Maybe<String>;
  opt1_gte?: Maybe<String>;
  opt1_contains?: Maybe<String>;
  opt1_not_contains?: Maybe<String>;
  opt1_starts_with?: Maybe<String>;
  opt1_not_starts_with?: Maybe<String>;
  opt1_ends_with?: Maybe<String>;
  opt1_not_ends_with?: Maybe<String>;
  opt2?: Maybe<String>;
  opt2_not?: Maybe<String>;
  opt2_in?: Maybe<String[] | String>;
  opt2_not_in?: Maybe<String[] | String>;
  opt2_lt?: Maybe<String>;
  opt2_lte?: Maybe<String>;
  opt2_gt?: Maybe<String>;
  opt2_gte?: Maybe<String>;
  opt2_contains?: Maybe<String>;
  opt2_not_contains?: Maybe<String>;
  opt2_starts_with?: Maybe<String>;
  opt2_not_starts_with?: Maybe<String>;
  opt2_ends_with?: Maybe<String>;
  opt2_not_ends_with?: Maybe<String>;
  opt3?: Maybe<String>;
  opt3_not?: Maybe<String>;
  opt3_in?: Maybe<String[] | String>;
  opt3_not_in?: Maybe<String[] | String>;
  opt3_lt?: Maybe<String>;
  opt3_lte?: Maybe<String>;
  opt3_gt?: Maybe<String>;
  opt3_gte?: Maybe<String>;
  opt3_contains?: Maybe<String>;
  opt3_not_contains?: Maybe<String>;
  opt3_starts_with?: Maybe<String>;
  opt3_not_starts_with?: Maybe<String>;
  opt3_ends_with?: Maybe<String>;
  opt3_not_ends_with?: Maybe<String>;
  opt4?: Maybe<String>;
  opt4_not?: Maybe<String>;
  opt4_in?: Maybe<String[] | String>;
  opt4_not_in?: Maybe<String[] | String>;
  opt4_lt?: Maybe<String>;
  opt4_lte?: Maybe<String>;
  opt4_gt?: Maybe<String>;
  opt4_gte?: Maybe<String>;
  opt4_contains?: Maybe<String>;
  opt4_not_contains?: Maybe<String>;
  opt4_starts_with?: Maybe<String>;
  opt4_not_starts_with?: Maybe<String>;
  opt4_ends_with?: Maybe<String>;
  opt4_not_ends_with?: Maybe<String>;
  id?: Maybe<String>;
  id_not?: Maybe<String>;
  id_in?: Maybe<String[] | String>;
  id_not_in?: Maybe<String[] | String>;
  id_lt?: Maybe<String>;
  id_lte?: Maybe<String>;
  id_gt?: Maybe<String>;
  id_gte?: Maybe<String>;
  id_contains?: Maybe<String>;
  id_not_contains?: Maybe<String>;
  id_starts_with?: Maybe<String>;
  id_not_starts_with?: Maybe<String>;
  id_ends_with?: Maybe<String>;
  id_not_ends_with?: Maybe<String>;
  AND?: Maybe<ObjScalarWhereInput[] | ObjScalarWhereInput>;
  OR?: Maybe<ObjScalarWhereInput[] | ObjScalarWhereInput>;
  NOT?: Maybe<ObjScalarWhereInput[] | ObjScalarWhereInput>;
}

export interface ObjUpdateManyWithWhereNestedInput {
  where: ObjScalarWhereInput;
  data: ObjUpdateManyDataInput;
}

export interface ObjUpdateManyDataInput {
  opt1?: Maybe<String>;
  opt2?: Maybe<String>;
  opt3?: Maybe<String>;
  opt4?: Maybe<String>;
  id?: Maybe<String>;
}

export interface QuestionAddUpdateManyMutationInput {
  course?: Maybe<String>;
  name?: Maybe<String>;
  desc?: Maybe<String>;
  exp?: Maybe<String>;
  ans?: Maybe<String>;
}

export interface UserCreateInput {
  username: String;
  password: String;
  name: String;
  campus?: Maybe<String>;
  department?: Maybe<String>;
  dob?: Maybe<DateTimeInput>;
  email: String;
  level: Int;
  id?: Maybe<ID_Input>;
}

export interface UserUpdateInput {
  username?: Maybe<String>;
  password?: Maybe<String>;
  name?: Maybe<String>;
  campus?: Maybe<String>;
  department?: Maybe<String>;
  dob?: Maybe<DateTimeInput>;
  email?: Maybe<String>;
  level?: Maybe<Int>;
}

export interface UserUpdateManyMutationInput {
  username?: Maybe<String>;
  password?: Maybe<String>;
  name?: Maybe<String>;
  campus?: Maybe<String>;
  department?: Maybe<String>;
  dob?: Maybe<DateTimeInput>;
  email?: Maybe<String>;
  level?: Maybe<Int>;
}

export interface BranchSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<BranchWhereInput>;
  AND?: Maybe<BranchSubscriptionWhereInput[] | BranchSubscriptionWhereInput>;
}

export interface CampusSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<CampusWhereInput>;
  AND?: Maybe<CampusSubscriptionWhereInput[] | CampusSubscriptionWhereInput>;
}

export interface CourseSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<CourseWhereInput>;
  AND?: Maybe<CourseSubscriptionWhereInput[] | CourseSubscriptionWhereInput>;
}

export interface GlobalSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<GlobalWhereInput>;
  AND?: Maybe<GlobalSubscriptionWhereInput[] | GlobalSubscriptionWhereInput>;
}

export interface QuestionAddSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<QuestionAddWhereInput>;
  AND?: Maybe<
    QuestionAddSubscriptionWhereInput[] | QuestionAddSubscriptionWhereInput
  >;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<UserWhereInput>;
  AND?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>;
}

export interface NodeNode {
  id: ID_Output;
}

export interface Branch {
  id: ID_Output;
  name: String;
}

export interface BranchPromise extends Promise<Branch>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface BranchSubscription
  extends Promise<AsyncIterator<Branch>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface BranchNullablePromise
  extends Promise<Branch | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface BranchConnection {
  pageInfo: PageInfo;
  edges: BranchEdge[];
}

export interface BranchConnectionPromise
  extends Promise<BranchConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<BranchEdge>>() => T;
  aggregate: <T = AggregateBranchPromise>() => T;
}

export interface BranchConnectionSubscription
  extends Promise<AsyncIterator<BranchConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<BranchEdgeSubscription>>>() => T;
  aggregate: <T = AggregateBranchSubscription>() => T;
}

export interface PageInfo {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface BranchEdge {
  node: Branch;
  cursor: String;
}

export interface BranchEdgePromise extends Promise<BranchEdge>, Fragmentable {
  node: <T = BranchPromise>() => T;
  cursor: () => Promise<String>;
}

export interface BranchEdgeSubscription
  extends Promise<AsyncIterator<BranchEdge>>,
    Fragmentable {
  node: <T = BranchSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateBranch {
  count: Int;
}

export interface AggregateBranchPromise
  extends Promise<AggregateBranch>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateBranchSubscription
  extends Promise<AsyncIterator<AggregateBranch>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface Campus {
  id: ID_Output;
  admin_id: String;
  departments?: <T = FragmentableArray<Tag>>() => T;
  name: String;
}

export interface CampusPromise extends Promise<Campus>, Fragmentable {
  id: () => Promise<ID_Output>;
  admin_id: () => Promise<String>;
  departments: <T = FragmentableArray<Tag>>() => T;
  name: () => Promise<String>;
}

export interface CampusSubscription
  extends Promise<AsyncIterator<Campus>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  admin_id: () => Promise<AsyncIterator<String>>;
  departments: <T = Promise<AsyncIterator<TagSubscription>>>() => T;
  name: () => Promise<AsyncIterator<String>>;
}

export interface CampusNullablePromise
  extends Promise<Campus | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  admin_id: () => Promise<String>;
  departments: <T = FragmentableArray<Tag>>() => T;
  name: () => Promise<String>;
}

export interface Tag {
  name: String;
  id: String;
}

export interface TagPromise extends Promise<Tag>, Fragmentable {
  name: () => Promise<String>;
  id: () => Promise<String>;
}

export interface TagSubscription
  extends Promise<AsyncIterator<Tag>>,
    Fragmentable {
  name: () => Promise<AsyncIterator<String>>;
  id: () => Promise<AsyncIterator<String>>;
}

export interface TagNullablePromise extends Promise<Tag | null>, Fragmentable {
  name: () => Promise<String>;
  id: () => Promise<String>;
}

export interface CampusConnection {
  pageInfo: PageInfo;
  edges: CampusEdge[];
}

export interface CampusConnectionPromise
  extends Promise<CampusConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<CampusEdge>>() => T;
  aggregate: <T = AggregateCampusPromise>() => T;
}

export interface CampusConnectionSubscription
  extends Promise<AsyncIterator<CampusConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<CampusEdgeSubscription>>>() => T;
  aggregate: <T = AggregateCampusSubscription>() => T;
}

export interface CampusEdge {
  node: Campus;
  cursor: String;
}

export interface CampusEdgePromise extends Promise<CampusEdge>, Fragmentable {
  node: <T = CampusPromise>() => T;
  cursor: () => Promise<String>;
}

export interface CampusEdgeSubscription
  extends Promise<AsyncIterator<CampusEdge>>,
    Fragmentable {
  node: <T = CampusSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateCampus {
  count: Int;
}

export interface AggregateCampusPromise
  extends Promise<AggregateCampus>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateCampusSubscription
  extends Promise<AsyncIterator<AggregateCampus>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface Course {
  id: ID_Output;
  branch: String;
  coordinator_id: String;
  name: String;
}

export interface CoursePromise extends Promise<Course>, Fragmentable {
  id: () => Promise<ID_Output>;
  branch: () => Promise<String>;
  coordinator_id: () => Promise<String>;
  name: () => Promise<String>;
}

export interface CourseSubscription
  extends Promise<AsyncIterator<Course>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  branch: () => Promise<AsyncIterator<String>>;
  coordinator_id: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface CourseNullablePromise
  extends Promise<Course | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  branch: () => Promise<String>;
  coordinator_id: () => Promise<String>;
  name: () => Promise<String>;
}

export interface CourseConnection {
  pageInfo: PageInfo;
  edges: CourseEdge[];
}

export interface CourseConnectionPromise
  extends Promise<CourseConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<CourseEdge>>() => T;
  aggregate: <T = AggregateCoursePromise>() => T;
}

export interface CourseConnectionSubscription
  extends Promise<AsyncIterator<CourseConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<CourseEdgeSubscription>>>() => T;
  aggregate: <T = AggregateCourseSubscription>() => T;
}

export interface CourseEdge {
  node: Course;
  cursor: String;
}

export interface CourseEdgePromise extends Promise<CourseEdge>, Fragmentable {
  node: <T = CoursePromise>() => T;
  cursor: () => Promise<String>;
}

export interface CourseEdgeSubscription
  extends Promise<AsyncIterator<CourseEdge>>,
    Fragmentable {
  node: <T = CourseSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateCourse {
  count: Int;
}

export interface AggregateCoursePromise
  extends Promise<AggregateCourse>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateCourseSubscription
  extends Promise<AsyncIterator<AggregateCourse>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface Global {
  regs?: Boolean;
  regf?: Boolean;
  id: String;
  _id: ID_Output;
}

export interface GlobalPromise extends Promise<Global>, Fragmentable {
  regs: () => Promise<Boolean>;
  regf: () => Promise<Boolean>;
  id: () => Promise<String>;
  _id: () => Promise<ID_Output>;
}

export interface GlobalSubscription
  extends Promise<AsyncIterator<Global>>,
    Fragmentable {
  regs: () => Promise<AsyncIterator<Boolean>>;
  regf: () => Promise<AsyncIterator<Boolean>>;
  id: () => Promise<AsyncIterator<String>>;
  _id: () => Promise<AsyncIterator<ID_Output>>;
}

export interface GlobalNullablePromise
  extends Promise<Global | null>,
    Fragmentable {
  regs: () => Promise<Boolean>;
  regf: () => Promise<Boolean>;
  id: () => Promise<String>;
  _id: () => Promise<ID_Output>;
}

export interface GlobalConnection {
  pageInfo: PageInfo;
  edges: GlobalEdge[];
}

export interface GlobalConnectionPromise
  extends Promise<GlobalConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<GlobalEdge>>() => T;
  aggregate: <T = AggregateGlobalPromise>() => T;
}

export interface GlobalConnectionSubscription
  extends Promise<AsyncIterator<GlobalConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<GlobalEdgeSubscription>>>() => T;
  aggregate: <T = AggregateGlobalSubscription>() => T;
}

export interface GlobalEdge {
  node: Global;
  cursor: String;
}

export interface GlobalEdgePromise extends Promise<GlobalEdge>, Fragmentable {
  node: <T = GlobalPromise>() => T;
  cursor: () => Promise<String>;
}

export interface GlobalEdgeSubscription
  extends Promise<AsyncIterator<GlobalEdge>>,
    Fragmentable {
  node: <T = GlobalSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateGlobal {
  count: Int;
}

export interface AggregateGlobalPromise
  extends Promise<AggregateGlobal>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateGlobalSubscription
  extends Promise<AsyncIterator<AggregateGlobal>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface QuestionAdd {
  id: ID_Output;
  course: String;
  name: String;
  desc: String;
  exp: String;
  opt?: <T = FragmentableArray<Obj>>() => T;
  ans: String;
}

export interface QuestionAddPromise extends Promise<QuestionAdd>, Fragmentable {
  id: () => Promise<ID_Output>;
  course: () => Promise<String>;
  name: () => Promise<String>;
  desc: () => Promise<String>;
  exp: () => Promise<String>;
  opt: <T = FragmentableArray<Obj>>() => T;
  ans: () => Promise<String>;
}

export interface QuestionAddSubscription
  extends Promise<AsyncIterator<QuestionAdd>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  course: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
  desc: () => Promise<AsyncIterator<String>>;
  exp: () => Promise<AsyncIterator<String>>;
  opt: <T = Promise<AsyncIterator<ObjSubscription>>>() => T;
  ans: () => Promise<AsyncIterator<String>>;
}

export interface QuestionAddNullablePromise
  extends Promise<QuestionAdd | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  course: () => Promise<String>;
  name: () => Promise<String>;
  desc: () => Promise<String>;
  exp: () => Promise<String>;
  opt: <T = FragmentableArray<Obj>>() => T;
  ans: () => Promise<String>;
}

export interface Obj {
  opt1: String;
  opt2: String;
  opt3: String;
  opt4: String;
  id: String;
}

export interface ObjPromise extends Promise<Obj>, Fragmentable {
  opt1: () => Promise<String>;
  opt2: () => Promise<String>;
  opt3: () => Promise<String>;
  opt4: () => Promise<String>;
  id: () => Promise<String>;
}

export interface ObjSubscription
  extends Promise<AsyncIterator<Obj>>,
    Fragmentable {
  opt1: () => Promise<AsyncIterator<String>>;
  opt2: () => Promise<AsyncIterator<String>>;
  opt3: () => Promise<AsyncIterator<String>>;
  opt4: () => Promise<AsyncIterator<String>>;
  id: () => Promise<AsyncIterator<String>>;
}

export interface ObjNullablePromise extends Promise<Obj | null>, Fragmentable {
  opt1: () => Promise<String>;
  opt2: () => Promise<String>;
  opt3: () => Promise<String>;
  opt4: () => Promise<String>;
  id: () => Promise<String>;
}

export interface QuestionAddConnection {
  pageInfo: PageInfo;
  edges: QuestionAddEdge[];
}

export interface QuestionAddConnectionPromise
  extends Promise<QuestionAddConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<QuestionAddEdge>>() => T;
  aggregate: <T = AggregateQuestionAddPromise>() => T;
}

export interface QuestionAddConnectionSubscription
  extends Promise<AsyncIterator<QuestionAddConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<QuestionAddEdgeSubscription>>>() => T;
  aggregate: <T = AggregateQuestionAddSubscription>() => T;
}

export interface QuestionAddEdge {
  node: QuestionAdd;
  cursor: String;
}

export interface QuestionAddEdgePromise
  extends Promise<QuestionAddEdge>,
    Fragmentable {
  node: <T = QuestionAddPromise>() => T;
  cursor: () => Promise<String>;
}

export interface QuestionAddEdgeSubscription
  extends Promise<AsyncIterator<QuestionAddEdge>>,
    Fragmentable {
  node: <T = QuestionAddSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateQuestionAdd {
  count: Int;
}

export interface AggregateQuestionAddPromise
  extends Promise<AggregateQuestionAdd>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateQuestionAddSubscription
  extends Promise<AsyncIterator<AggregateQuestionAdd>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface User {
  username: String;
  password: String;
  name: String;
  campus?: String;
  department?: String;
  dob?: DateTimeOutput;
  email: String;
  level: Int;
  id: ID_Output;
}

export interface UserPromise extends Promise<User>, Fragmentable {
  username: () => Promise<String>;
  password: () => Promise<String>;
  name: () => Promise<String>;
  campus: () => Promise<String>;
  department: () => Promise<String>;
  dob: () => Promise<DateTimeOutput>;
  email: () => Promise<String>;
  level: () => Promise<Int>;
  id: () => Promise<ID_Output>;
}

export interface UserSubscription
  extends Promise<AsyncIterator<User>>,
    Fragmentable {
  username: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
  campus: () => Promise<AsyncIterator<String>>;
  department: () => Promise<AsyncIterator<String>>;
  dob: () => Promise<AsyncIterator<DateTimeOutput>>;
  email: () => Promise<AsyncIterator<String>>;
  level: () => Promise<AsyncIterator<Int>>;
  id: () => Promise<AsyncIterator<ID_Output>>;
}

export interface UserNullablePromise
  extends Promise<User | null>,
    Fragmentable {
  username: () => Promise<String>;
  password: () => Promise<String>;
  name: () => Promise<String>;
  campus: () => Promise<String>;
  department: () => Promise<String>;
  dob: () => Promise<DateTimeOutput>;
  email: () => Promise<String>;
  level: () => Promise<Int>;
  id: () => Promise<ID_Output>;
}

export interface UserConnection {
  pageInfo: PageInfo;
  edges: UserEdge[];
}

export interface UserConnectionPromise
  extends Promise<UserConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<UserEdge>>() => T;
  aggregate: <T = AggregateUserPromise>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface UserEdge {
  node: User;
  cursor: String;
}

export interface UserEdgePromise extends Promise<UserEdge>, Fragmentable {
  node: <T = UserPromise>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdge>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateUser {
  count: Int;
}

export interface AggregateUserPromise
  extends Promise<AggregateUser>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUser>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface BatchPayload {
  count: Long;
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface BranchSubscriptionPayload {
  mutation: MutationType;
  node: Branch;
  updatedFields: String[];
  previousValues: BranchPreviousValues;
}

export interface BranchSubscriptionPayloadPromise
  extends Promise<BranchSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = BranchPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = BranchPreviousValuesPromise>() => T;
}

export interface BranchSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<BranchSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = BranchSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = BranchPreviousValuesSubscription>() => T;
}

export interface BranchPreviousValues {
  id: ID_Output;
  name: String;
}

export interface BranchPreviousValuesPromise
  extends Promise<BranchPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
}

export interface BranchPreviousValuesSubscription
  extends Promise<AsyncIterator<BranchPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface CampusSubscriptionPayload {
  mutation: MutationType;
  node: Campus;
  updatedFields: String[];
  previousValues: CampusPreviousValues;
}

export interface CampusSubscriptionPayloadPromise
  extends Promise<CampusSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = CampusPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = CampusPreviousValuesPromise>() => T;
}

export interface CampusSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<CampusSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = CampusSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = CampusPreviousValuesSubscription>() => T;
}

export interface CampusPreviousValues {
  id: ID_Output;
  admin_id: String;
  name: String;
}

export interface CampusPreviousValuesPromise
  extends Promise<CampusPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  admin_id: () => Promise<String>;
  name: () => Promise<String>;
}

export interface CampusPreviousValuesSubscription
  extends Promise<AsyncIterator<CampusPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  admin_id: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface CourseSubscriptionPayload {
  mutation: MutationType;
  node: Course;
  updatedFields: String[];
  previousValues: CoursePreviousValues;
}

export interface CourseSubscriptionPayloadPromise
  extends Promise<CourseSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = CoursePromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = CoursePreviousValuesPromise>() => T;
}

export interface CourseSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<CourseSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = CourseSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = CoursePreviousValuesSubscription>() => T;
}

export interface CoursePreviousValues {
  id: ID_Output;
  branch: String;
  coordinator_id: String;
  name: String;
}

export interface CoursePreviousValuesPromise
  extends Promise<CoursePreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  branch: () => Promise<String>;
  coordinator_id: () => Promise<String>;
  name: () => Promise<String>;
}

export interface CoursePreviousValuesSubscription
  extends Promise<AsyncIterator<CoursePreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  branch: () => Promise<AsyncIterator<String>>;
  coordinator_id: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
}

export interface GlobalSubscriptionPayload {
  mutation: MutationType;
  node: Global;
  updatedFields: String[];
  previousValues: GlobalPreviousValues;
}

export interface GlobalSubscriptionPayloadPromise
  extends Promise<GlobalSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = GlobalPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = GlobalPreviousValuesPromise>() => T;
}

export interface GlobalSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<GlobalSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = GlobalSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = GlobalPreviousValuesSubscription>() => T;
}

export interface GlobalPreviousValues {
  regs?: Boolean;
  regf?: Boolean;
  id: String;
  _id: ID_Output;
}

export interface GlobalPreviousValuesPromise
  extends Promise<GlobalPreviousValues>,
    Fragmentable {
  regs: () => Promise<Boolean>;
  regf: () => Promise<Boolean>;
  id: () => Promise<String>;
  _id: () => Promise<ID_Output>;
}

export interface GlobalPreviousValuesSubscription
  extends Promise<AsyncIterator<GlobalPreviousValues>>,
    Fragmentable {
  regs: () => Promise<AsyncIterator<Boolean>>;
  regf: () => Promise<AsyncIterator<Boolean>>;
  id: () => Promise<AsyncIterator<String>>;
  _id: () => Promise<AsyncIterator<ID_Output>>;
}

export interface QuestionAddSubscriptionPayload {
  mutation: MutationType;
  node: QuestionAdd;
  updatedFields: String[];
  previousValues: QuestionAddPreviousValues;
}

export interface QuestionAddSubscriptionPayloadPromise
  extends Promise<QuestionAddSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = QuestionAddPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = QuestionAddPreviousValuesPromise>() => T;
}

export interface QuestionAddSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<QuestionAddSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = QuestionAddSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = QuestionAddPreviousValuesSubscription>() => T;
}

export interface QuestionAddPreviousValues {
  id: ID_Output;
  course: String;
  name: String;
  desc: String;
  exp: String;
  ans: String;
}

export interface QuestionAddPreviousValuesPromise
  extends Promise<QuestionAddPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  course: () => Promise<String>;
  name: () => Promise<String>;
  desc: () => Promise<String>;
  exp: () => Promise<String>;
  ans: () => Promise<String>;
}

export interface QuestionAddPreviousValuesSubscription
  extends Promise<AsyncIterator<QuestionAddPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  course: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
  desc: () => Promise<AsyncIterator<String>>;
  exp: () => Promise<AsyncIterator<String>>;
  ans: () => Promise<AsyncIterator<String>>;
}

export interface UserSubscriptionPayload {
  mutation: MutationType;
  node: User;
  updatedFields: String[];
  previousValues: UserPreviousValues;
}

export interface UserSubscriptionPayloadPromise
  extends Promise<UserSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = UserPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValuesPromise>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface UserPreviousValues {
  username: String;
  password: String;
  name: String;
  campus?: String;
  department?: String;
  dob?: DateTimeOutput;
  email: String;
  level: Int;
  id: ID_Output;
}

export interface UserPreviousValuesPromise
  extends Promise<UserPreviousValues>,
    Fragmentable {
  username: () => Promise<String>;
  password: () => Promise<String>;
  name: () => Promise<String>;
  campus: () => Promise<String>;
  department: () => Promise<String>;
  dob: () => Promise<DateTimeOutput>;
  email: () => Promise<String>;
  level: () => Promise<Int>;
  id: () => Promise<ID_Output>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValues>>,
    Fragmentable {
  username: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
  name: () => Promise<AsyncIterator<String>>;
  campus: () => Promise<AsyncIterator<String>>;
  department: () => Promise<AsyncIterator<String>>;
  dob: () => Promise<AsyncIterator<DateTimeOutput>>;
  email: () => Promise<AsyncIterator<String>>;
  level: () => Promise<AsyncIterator<Int>>;
  id: () => Promise<AsyncIterator<ID_Output>>;
}

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

export type Long = string;

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: "User",
    embedded: false
  },
  {
    name: "Global",
    embedded: false
  },
  {
    name: "Tag",
    embedded: true
  },
  {
    name: "Campus",
    embedded: false
  },
  {
    name: "Branch",
    embedded: false
  },
  {
    name: "Course",
    embedded: false
  },
  {
    name: "QuestionAdd",
    embedded: false
  },
  {
    name: "Obj",
    embedded: true
  }
];

/**
 * Type Defs
 */

export const prisma: Prisma;
